Description of gvArrayRef
gvArrayRef
PURPOSE
% gvArrayRef - GIMBL-Vis multidimensional data handle class wrapper for gvArray
SYNOPSIS
This is a script file.
DESCRIPTION
% gvArrayRef - GIMBL-Vis multidimensional data handle class wrapper for gvArray
 Description: The gvArrayRef class inherets from the MDDRef class. It uses
              gvArray instead of MDD as its value object property.
 Author: Erik Roberts
CROSS-REFERENCE INFORMATION
This function calls:
gvArray % gvArray - GIMBL-Vis multidimensional data storage class
gvArrayRef % gvArrayRef - GIMBL-Vis multidimensional data handle class wrapper for gvArray
This function is called by:
gv % gv - main class for GIMBL-Vis
gvModel % gvModel - Model class for the GIMBL-Vis Model-View-Controller
importDataFromWorkspace importDataFromWorkspace
importDsData importDsData - import dynasim data
gvArrayRef % gvArrayRef - GIMBL-Vis multidimensional data handle class wrapper for gvArray
applyFn
SUBFUNCTIONS
function obj = gvArrayRef(varargin)
function gvArrayCast(obj)
SOURCE CODE
%% gvArrayRef - GIMBL-Vis multidimensional data handle class wrapper for gvArray
%
% Description: The gvArrayRef class inherets from the MDDRef class. It uses
%              gvArray instead of MDD as its value object property.
%
% Author: Erik Roberts
classdef gvArrayRef < MDDRef & matlab.mixin.Copyable
  properties (Access = private, SetObservable) % allows listener callback, aborts if set to current value
    valueObj
    valueObjClass = gvArray
  end
  methods
    function obj = gvArrayRef(varargin)
      metaObj = ?gvArrayRef;
      valueObjClass = metaObj.PropertyList(strcmp('valueObjClass', {metaObj.PropertyList.Name})).DefaultValue;
      obj@MDDRef(valueObjClass, varargin{:});
    end
    function gvArrayCast(obj)
      obj.valueObj = gvArray(obj.valueObj);
    end
  end
end