Description of gvEvent
gvEvent
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
gvEvent
This function is called by:
gvController % gvController - Controller class for the GIMBL-Vis Model-View-Controller
gvEvent
gvSelectPlugin % gvSelectPlugin - Select GUI Plugin Class for GIMBL-Vis
SUBFUNCTIONS
function eventData = gvEvent(varargin)
SOURCE CODE
classdef (ConstructOnLoad) gvEvent < event.EventData
  %% gvEvent - event class for GIMBL-Vis
  %
  % Description: This subclass of event.EventData permits storage of data. If
  % the constructor is passed a char cast of a numeric, it will be recast to a
  % numeric.
  properties
    data
  end
  methods
    function eventData = gvEvent(varargin)
      if ~nargin
        data = [];
      elseif nargin == 1
        data = varargin{1};
      else
        data = struct(varargin{:}); % key-value pairs
      end
      % convert string to double if possible
      if ischar(data) && ~isnan(str2double(data))
        data = str2double(data);
      end
      eventData.data = data;
    end
  end
end