Description of gvWindowPlugin
gvWindowPlugin
PURPOSE
% gvWindow - Abstract UI Window Plugin Class for GIMBL-Vis
SYNOPSIS
This is a script file.
DESCRIPTION
% gvWindow - Abstract UI Window Plugin Class for GIMBL-Vis
 Description: This abstract class provides a template interface for GIMBL-Vis
              window plugins
CROSS-REFERENCE INFORMATION
This function calls:
makeFig
openWindow check for main window
gvGuiPlugin % gvGuiPlugin - Abstract GUI Plugin Class for GIMBL-Vis
gvWindowPlugin % gvWindow - Abstract UI Window Plugin Class for GIMBL-Vis
openWindow check for main window
openWindow check for main window
This function is called by:
gvMainWindowPlugin % gvMainWindowPlugin - Main Window Class for GIMBL-Vis
gvWindowPlugin % gvWindow - Abstract UI Window Plugin Class for GIMBL-Vis
gvImageWindowPlugin % gvImageWindowPlugin - Image Window Plugin Class for GIMBL-Vis
gvPlotWindowPlugin % gvPlotWindowPlugin - Plot Window Plugin Class for GIMBL-Vis
SUBFUNCTIONS
function pluginObj = gvWindowPlugin(varargin)
function closeWindow(pluginObj)
function windowExistBool = checkWindowExists(pluginObj)
function Callback_resetWindow(src, evnt)
SOURCE CODE
%% gvWindow - Abstract UI Window Plugin Class for GIMBL-Vis
%
% Description: This abstract class provides a template interface for GIMBL-Vis
%              window plugins
classdef (Abstract) gvWindowPlugin < gvGuiPlugin
  %% Abstract Properties %%
  properties (Abstract, Constant)
    windowName
  end
  %% Events %%
  events
    windowOpened
  end
  %% Abstract Methods %%
  methods (Abstract)
     openWindow(pluginObj)
  end
  methods (Abstract, Access = protected)
    makeFig(pluginObj)
  end
  %% Concrete Methods %%
  methods
    function pluginObj = gvWindowPlugin(varargin)
      % superclass constructor
      pluginObj@gvGuiPlugin(varargin{:});
      % default values
      pluginObj.handles.fig = [];
    end
    function closeWindow(pluginObj)
      figH = pluginObj.handles.fig;
      windowExistBool = pluginObj.checkWindowExists();
      if windowExistBool
        delete(figH);
        pluginObj.handles.fig = [];
      end
    end
    function windowExistBool = checkWindowExists(pluginObj)
      figH = pluginObj.handles.fig;
      windowExistBool = isValidFigHandle(figH);
    end
  end
  %% Static Methods %%
  methods (Static)
    function Callback_resetWindow(src, evnt)
      pluginObj = src.UserData.pluginObj;
      pluginObj.openWindow(); % reopen window
    end
  end
end