Description of minimalPlugin
minimalPlugin
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
gvPlugin % gvPlugin - Abstract Plugin Class for GIMBL-Vis
minimalPlugin
This function is called by:
minimalPlugin
SUBFUNCTIONS
function out = makePanelControls(pluginObj, parentHandle)
SOURCE CODE
classdef minimalPlugin < gvPlugin
  %% Public properties %%
  properties (Constant)
    pluginName = 'MinimalPlugin'
    pluginFieldName = 'minimalPlugin'
  end
  properties
    metadata
    handles
  end
  %% Public methods %%
  methods
    function out = makePanelControls(pluginObj, parentHandle)
      out = uix.Empty('Parent',parentHandle);
    end
  end
end