Description of gvGetAxisType
gvGetAxisType
PURPOSE
gvGetAxisType - get axis type from axismeta of mdd object
SYNOPSIS
function dataAxesType = gvGetAxisType(mddObj)
DESCRIPTION
 gvGetAxisType - get axis type from axismeta of mdd object
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Callback_mouseMove
getPlotMetadataFromData getPlotMetadataFromData - get plotting and legend metadata from data and
openLegendWindow % gvLegendWindow - UI Legend Window Class for GIMBL-Vis
plot TODO
SUBFUNCTIONS
function axisType = getAxisType(s)
SOURCE CODE
function dataAxesType = gvGetAxisType(mddObj)
% gvGetAxisType - get axis type from axismeta of mdd object
dataAxes = mddObj.axis;
dataAxesMeta = {dataAxes.axismeta};
dataAxesType = cellfunu(@getAxisType, dataAxesMeta);
if all(cellfun(@isempty, dataAxesType))
  dataAxesType = [];
end
  function axisType = getAxisType(s)
    if isfield(s, 'axisType')
      axisType = s.axisType;
    else
      axisType = [];
    end
  end
end