Description of openWindow
openWindow
PURPOSE
check for main window
SYNOPSIS
function openWindow(pluginObj)
DESCRIPTION
 check for main window
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gvMainWindowPlugin % gvMainWindowPlugin - Main Window Class for GIMBL-Vis
gvWindowPlugin % gvWindow - Abstract UI Window Plugin Class for GIMBL-Vis
gvImageWindowPlugin % gvImageWindowPlugin - Image Window Plugin Class for GIMBL-Vis
gvPlotWindowPlugin % gvPlotWindowPlugin - Plot Window Plugin Class for GIMBL-Vis
SOURCE CODE
function openWindow(pluginObj)
% check for main window
warnBool = true;
mainWindowExistBool = pluginObj.view.checkMainWindowExists(warnBool);
if mainWindowExistBool
  % check for plot window
  plotWindowExistBool = pluginObj.checkWindowExists();
  if plotWindowExistBool
    pluginObj.vprintf('gvPlotWindowPlugin: Reopening plot window\n')
    % delete plot window handles
    delete(pluginObj.handles.fig)
    delete(pluginObj.handles.ax)
  end
  % Make New Panel
  pluginObj.makeFig();
  % Add listeners
%   addlistener(pluginObj, 'plotEvent', @gvPlotWindowPlugin.plotCallback);
  % TODO check if needed
  % Data cursor
  pluginObj.addDataCursor();
  % Make Axes/Update Panel
  pluginObj.makeAxes();
  notify(pluginObj, 'windowOpened');
  % Plot
  pluginObj.plot();
end
end % main fn